# Generated by Django 5.1.4 on 2025-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_booking_subcategory_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='category_images/'),
        ),
    ]
