# Generated by Django 5.1.4 on 2025-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.ImageField(blank=True, upload_to='subcategory_images/'),
        ),
    ]
